---
  # Helps to disambiguate sudo/become behavior.
- name: Display target username for dotfiles management.
  debug:
    msg: >-
      Configuring dotfiles for user '{{ dotfiles_username }}'.

- include_tasks: github_config.yml
  when: dotfiles_repo_url.startswith('git@github.com')
  tags: github_config

- include_tasks: homeshick.yml

- include_tasks: oh_my_zsh.yml
  when: dotfiles_include_oh_my_zsh == true

- include_tasks: vim.yml

- include_tasks: liquidprompt.yml
  when: dotfiles_include_liquidprompt == true
